/**
 * Supabase database types — generated by the Supabase CLI.
 *
 * To regenerate after schema changes:
 *   npx supabase gen types typescript --project-id <project-ref> > src/types/supabase.ts
 *
 * Until generation is set up, this file provides a minimal placeholder
 * that satisfies TypeScript without importing the full generated output.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

/** Placeholder — replace with `supabase gen types` output */
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          role: 'customer' | 'staff' | 'founder'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          role?: 'customer' | 'staff' | 'founder'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          role?: 'customer' | 'staff' | 'founder'
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: 'customer' | 'staff' | 'founder'
    }
  }
}
